POST /api/2.3/tenders/ec0d570d065945b0bea0c78b3b9b9941/ownership HTTP/1.0
Authorization: Basic YnJva2VyMjo=
Content-Length: 100
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "transfer": "042fdce9954d4413a7363ef59460c989", 
    "id": "36e1a99828133d3265eadcd0480874a4"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.enquiries", 
    "tenderID": "UA-2016-06-30-000001", 
    "tenderPeriod": {
      "startDate": "2016-07-07T19:19:24.248650+03:00", 
      "endDate": "2016-07-14T19:19:24.248650+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-07-02T19:19:24.248650+03:00", 
          "endDate": "2016-07-05T19:19:24.248650+03:00"
        }, 
        "id": "a1ca5d4dc54f4519b8ade67ba798f771", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "procurementMethodType": "belowThreshold", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "numberOfBids": 0, 
    "next_check": "2016-07-07T19:19:24.248650+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "enquiryPeriod": {
      "startDate": "2016-06-30T19:19:25.419892+03:00", 
      "endDate": "2016-07-07T19:19:24.248650+03:00"
    }, 
    "owner": "broker2", 
    "dateModified": "2016-06-30T19:19:25.713923+03:00", 
    "id": "ec0d570d065945b0bea0c78b3b9b9941", 
    "awardCriteria": "lowestCost"
  }
}

