POST /api/2.2/transfers HTTP/1.0
Authorization: Basic YnJva2VyMjo=
Content-Length: 12
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {}
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
{
  "access": {
    "transfer": "8a1095be54de45a684b1bb46d5c427c5", 
    "token": "84321997ad424ae5a1be40c193f5cac2"
  }, 
  "data": {
    "date": "2016-06-30T21:41:01.752346+03:00", 
    "id": "578e6951f2b286f3154d9d7f8100be60"
  }
}

