POST /api/2.3/transfers HTTP/1.0
Authorization: Basic YnJva2VyMzo=
Content-Length: 12
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {}
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
{
  "access": {
    "transfer": "077ab6cb05cc412bb0f022f379cc9b90", 
    "token": "147acf9ebc0b4444b9711f062541fba4"
  }, 
  "data": {
    "date": "2016-10-31T10:45:31.978060+02:00", 
    "id": "e6f71eacbe55d68091dde1942500cf1b"
  }
}

